version: '3.8'

services:
  music-to-easy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-to-easy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      # Mount logs directory (optional)
      - ./logs:/app/logs
    networks:
      - bot-network
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bot-network:
    driver: bridge

# Optional: For development with hot reload
  music-to-easy-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: music-to-easy-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - bot-network
    profiles:
      - dev
